[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
packages = ["twitscraper"]

[project]
name = "twitscraper"
version = "0.0.2"
dependencies = [
  "selenium",
  "selenium-firefox",
]

[project.optional-dependencies]
dev = [
  "pytest",
]
